GoogleCloudPlatform/k8s-cluster-bundle

pkg/converter/converter_test.go, pkg/patch/patch_test.go, pkg/testutil/testdata/etcd-server.yaml, pkg/testutil/testdata/kube-apiserver.yaml, pkg/testutil/testdata/kube-controller-manager.yaml, pkg/testutil/testdata/kube-scheduler.yaml, pkg/testutil/testdata/kubedns/deployment.yaml, pkg/testutil/testdata/kubedns/kubedns-full.yaml
Use the real repo, rather than rely on one of GCR's docker bug mitigations
=> gcr.io/google-containers -> k8s.gcr.io

pkg/commands/BUILD.bazel, pkg/commands/filter/BUILD.bazel, pkg/commands/filter/add_commands.go, pkg/commands/filter/doc.go, pkg/commands/filter/filter.go, pkg/commands/root.go, pkg/converter/converter.go, pkg/filter/BUILD.bazel, pkg/filter/doc.go, pkg/filter/filter.go, pkg/filter/filter_test.go
This PR adds a relatively simple command to filter objects, components from bundles.
An example of use:
```
bundlectl filter -f example-bundle.yaml --filter-type=objects --namespaces=kube-system
```
Removes all objects with namespace=kube-system
```
bundlectl filter -f example-bundle.yaml --filter-type=objects --namespaces=kube-system --keep-only
```
Keeps only objects with namespace=kube-system.
=> Add a relatively simple command to filter objects, components

pkg/converter/example_test.go, pkg/converter/kube.go, pkg/core/core.go, pkg/filter/filter_test.go, pkg/find/finder.go, pkg/find/finder_test.go, pkg/find/images_test.go, pkg/transformer/export_test.go, pkg/transformer/images_test.go, pkg/transformer/inline_test.go, pkg/validation/validate_bundle.go, pkg/validation/validate_bundle_test.go
Before, it was only possible to look up objects based on name. Now, any
part of the object ref key can be provided.
Fixes https://github.com/GoogleCloudPlatform/k8s-cluster-bundle/issues/33
=> Add smart object lookup.

pkg/converter/exporter.go
Oversight: the ObjectExporter was meant to be public, but it has a private objects field.
=> Make objects public in exporter so it can be instantiated.

pkg/converter/kube.go
This update adds a generic object struct-marshalling helper to make it a bit easier to unmarshall to various types (including K8S types).
=> Add a generic object struct-marshalling helper

pkg/validation/validate_bundle.go, pkg/validation/validate_bundle_test.go
This PR adds validation for the kind and API Version for the bundle and
the cluster components.
Fixes: https://github.com/GoogleCloudPlatform/k8s-cluster-bundle/issues/63
=> Add validation for kind / apiversion.

pkg/validation/BUILD.bazel, pkg/validation/validate_component.go, pkg/validation/validate_url.go, pkg/validation/validate_url_test.go
#97 
I added url validation following rules of Go’s net/url Parse.
=> Add URL validation #97

pkg/apis/bundle/v1alpha1/component_types.go, pkg/validate/validate_component.go, pkg/validate/validate_component_test.go
This PR adds AppVersion as a field to the component spec. Note that the
versioning is much less restrictive here than for the `version` field.
The app version will accept X.Y and X.Y.Z-blah.0 in addition to X.Y.Z
Note: This intentionally doesn't add requirements. I now see this more
as something that would live as a CRD in the component objects.
=> Add an AppVersion field to the ComponentSpec.

pkg/converter/muxer.go, pkg/testutil/BUILD.bazel, pkg/testutil/errors.go, pkg/wrapper/BUILD.bazel, pkg/wrapper/bundlewrapper.go, pkg/wrapper/bundlewrapper_test.go
The BundleWrapper object is a simple union type that's useful for doing
input/output of bundle objects. It contains some logic for ensuring that
only one of the various bundle objects is non-nil at a given time.
- Incremental progress on #116
- Depends on #129
=> Add bundlewrapper object for bundle I/O

pkg/build/BUILD.bazel, pkg/build/config_map_maker.go, pkg/build/config_map_maker_test.go, pkg/build/doc.go, pkg/build/inline.go, pkg/build/inline_integration_test.go, pkg/build/inline_test.go, pkg/wrapper/bundlewrapper_test.go
This PR reworks the inlining code in the following ways:
- Move to pkg/build, to set up for more building functionality.
- Remove relative path rewriting. The files must now all have absolute paths.
- Use the BundleBuilder/ComponentBuilder types, which get inlined to Bundle, Component types.
- Rewrite the tests from scratch to use a table-driven approach.
This was split out from #125
And is incremental progress on #116
Note: This has the downside of duplicating code between here and the
`pkg/inline` directory and also making the diffs / blame less clear. But
I think it's a bit easier to do incrementally this way.
=> Copy the inline code to pkg/build and rework to use Builder forms.

examples/component/etcd-component.yaml, examples/component/etcd-server.yaml, examples/component/options.yaml, pkg/commands/BUILD.bazel, pkg/commands/patch/BUILD.bazel, pkg/commands/patch/add_commands.go, pkg/commands/patch/patch.go, pkg/commands/root.go, pkg/converter/muxer.go, pkg/options/common.go, pkg/options/patchtmpl/patch.go
This adds a simple command for patching.
tested with:
`go run cmd/bundlectl/main.go patch --input-file=examples/component/etcd-component.yaml --options-file=examples/component/options.yaml --patch-annotations=build-label-test,build-label-test`
and 
`go run cmd/bundlectl/main.go patch --input-file=examples/component/etcd-component.yaml --options-file=examples/component/options.yaml`
=> Add a command for patching.

pkg/build/BUILD.bazel, pkg/build/inline.go, pkg/build/inline_test.go
I want Components coming out of ComponentBuilder to be applied via kubectl. This generates the name if it doesn't exist.
Fixes: #142
=> Generate the component name if it is not specified

examples/component/README.md, examples/component/etcd-component-builder.yaml, examples/component/etcd-server.yaml, examples/component/patches.yaml
This PR splits out patches into a separate YAML file. Additionally,
updated the README.md to discuss patches an how they are used.
=> Docs, examples cleanup for patches.

pkg/converter/BUILD.bazel, pkg/converter/decoder.go, pkg/converter/decoder_test.go, pkg/converter/encoder.go
Decoder and Encoder are far more common terms and much easier to understand.
=> Rename muxer/demuxer to decoder/encoder.

pkg/commands/patch/add_commands.go, pkg/commands/patch/patch.go, pkg/options/common.go, pkg/options/patchtmpl/patch.go, pkg/options/patchtmpl/patch_test.go, pkg/options/simpletemplate/simple_applier.go
With this change, any patch that has been applied to the component will be removed from it by default. It is override-able with a flag.
=> Implement stripping applied patches from the component

pkg/build/BUILD.bazel, pkg/build/patchbuild.go, pkg/build/patchbuild_test.go
This PR recursively looks through the target schema and creates template-parameters based on the keys that it finds in the `properties`.
=> Add support for nested properties during patch template building.

README.md
- Shorten some sections
- Remove some component set / bundle examples.
- Add examples of patching.
- Clarify language around compatibility
- Fix some examples.
- Move installation to the top.
Fixes: #161
=> Rework the top-level Readme, following the v0.9.0 release

pkg/find/finder.go
This rename more accurately reflects the intended functionality.
=> Rename ComponentsFromName to ComponentVersions

pkg/build/inline.go, pkg/build/inline_integration_test.go, pkg/build/inline_test.go, pkg/converter/converter_integration_test.go, pkg/converter/converter_test.go, pkg/converter/decoder.go, pkg/converter/encoder.go, pkg/converter/example_test.go, pkg/converter/exporter_test.go, pkg/filter/filter_test.go, pkg/find/finder_test.go, pkg/find/images_test.go, pkg/options/rawyamltmpl/raw_text_applier_test.go, pkg/options/simpletemplate/simple_applier_test.go, pkg/validate/validate_component_test.go
Fixes: #119
* Adds filename to error messages during encodeng.
* Removes demux/mux private methods that I missed
* Add slightly more helpful error messages in converting library
* Update inlining error messages during conversion.
* Clean up existing conversion error message usage.
=> Encoder/decoder cleanups.

config/crds/bundle_v1alpha1_bundlebuilder.yaml, pkg/apis/bundle/v1alpha1/BUILD.bazel, pkg/apis/bundle/v1alpha1/builder_types.go, pkg/apis/bundle/v1alpha1/helpers.go, pkg/apis/bundle/v1alpha1/helpers_test.go, pkg/apis/bundle/v1alpha1/zz_generated.deepcopy.go, pkg/build/inline.go, pkg/build/inline_test.go, pkg/commands/export/BUILD.bazel, pkg/commands/export/export.go, pkg/wrapper/BUILD.bazel, pkg/wrapper/bundlewrapper.go
* Change default component name to include component set name and
version when in a component set (prevents component sets from
overwriting other component sets components)
* Move Export code into wrapper so that it can be used when using this
code as a library rather than using the CLI.
* Exporting a Bundle now results in a ComponentSet and Components, rather than all objects of all components in the bundle.
=> Implement export of Bundle to ComponentSet

pkg/commands/BUILD.bazel, pkg/commands/build/add_commands.go, pkg/commands/build/build.go, pkg/commands/cmdlib/cmdlib.go, pkg/commands/export/add_commands.go, pkg/commands/export/export.go, pkg/commands/filter/add_commands.go, pkg/commands/filter/filter.go, pkg/commands/find/add_commands.go, pkg/commands/find/images.go, pkg/commands/patch/add_commands.go, pkg/commands/patch/patch.go, pkg/commands/root.go, pkg/commands/validate/add_commands.go, pkg/commands/validate/validate.go
This should allow us to run deeper tests of commands, by allowing tests
in each of the command directories to run:
```
AddCommandsInternal(...deps...).Execute().
```
Partial work on #126
=> Move file/std io to top-level to allow for dependency-injection.

examples/component/README.md, pkg/commands/build/add_commands.go, pkg/commands/build/build.go, pkg/commands/cmdlib/bundleio.go, pkg/commands/filter/add_commands.go, pkg/commands/filter/filter.go, pkg/commands/patch/add_commands.go, pkg/commands/patch/patch.go
This changes the string map flag to a more standard format, from
"foo,bar;biff,bam" to "foo=bar,biff=bam".
Fixes: #163
=> Change string-map flag to more standard format.

pkg/build/BUILD.bazel, pkg/build/bazel_init_test.go, pkg/build/inline_integration_test.go, pkg/converter/bazel_init_test.go, pkg/converter/converter_integration_test.go, pkg/testutil/testutil.go
This changes the cwd to the test-directory when run with Bazel. This makes testing much simpler *and* compatible with bazel \o/.
=> Chdir to the appropriate directory when run with bazel.

README.md, examples/BUILD.bazel, examples/cluster/BUILD.bazel, examples/component/BUILD.bazel, examples/patchbuilder/BUILD.bazel, examples/patchbuilder/bazel_init_test.go, examples/patchbuilder/component-test.yaml, examples/patchbuilder/component_test.go, pkg/build/BUILD.bazel, pkg/build/patchbuild.go, pkg/converter/BUILD.bazel, pkg/testutil/componentsuite/BUILD.bazel, pkg/testutil/componentsuite/bazel_init_test.go, pkg/testutil/componentsuite/componentsuite.go, pkg/testutil/componentsuite/componentsuite_test.go, pkg/testutil/componentsuite/schema.go
Run component tests with `go test`, but define test cases in YAML!
Boiler plate looks like:
```go
package patchbuilder
import (
"testing"
"github.com/GoogleCloudPlatform/k8s-cluster-bundle/pkg/testutil/componentsuite"
)
func TestComponentSuite(t *testing.T) {
componentsuite.Run(t, "component-test.yaml")
}
```
Example test file:
```yaml
componentFile: builder.yaml
rootDirectory: './'
testCases:
- description: Success
build:
options:
ImageTag: '2.0'
apply:
options:
Namespace: default
expect:
findSubstrs:
Deployment-helloweb:
- 'namespace: default'
- 'image: gcr.io/google-samples/hello-app:2.0'
Service-helloweb:
- 'targetPort: 8080'
- description: 'Error: no image Tag'
apply:
options:
Namespace: default
expect:
buildErrSubstr: 'ImageTag in body is required'
```
Fixes: #175
=> Add componentsuite, which adds functionality for testing components.

pkg/apis/bundle/v1alpha1/helpers_test.go, pkg/build/inline.go, pkg/build/patchbuild.go, pkg/build/patchbuild_test.go, pkg/commands/build/build.go, pkg/commands/cmdlib/bundleio.go, pkg/filter/filter.go, pkg/filter/filter_test.go, pkg/find/images_test.go, pkg/options/options.go, pkg/options/rawyamltmpl/raw_text_applier_test.go, pkg/options/simpletemplate/simple_applier_test.go, pkg/testutil/componentsuite/componentsuite.go, pkg/testutil/componentsuite/schema.go
- Fix some bad JSON tags in componentsuite.go
- Rename `build.BuildPatchTemplates` to `build.PatchTemplates` (and variants) to fix stutter
- Fix comment for filter.Partition and add a test
- Add comments for the template options in pkg/options
- Fix several unkeyed structs.
=> Clean up go lint and go vet warnings.

Gopkg.lock, Gopkg.toml, pkg/clientset/versioned/BUILD.bazel, pkg/clientset/versioned/clientset.go, pkg/commands/build/BUILD.bazel, pkg/commands/build/build.go, pkg/commands/cmdlib/BUILD.bazel, pkg/commands/cmdlib/bundleio.go, pkg/commands/cmdlib/cmdlib.go, pkg/commands/export/BUILD.bazel, pkg/commands/export/export.go, pkg/commands/filter/BUILD.bazel, pkg/commands/filter/filter.go, pkg/commands/find/BUILD.bazel, pkg/commands/find/images.go, pkg/commands/patch/BUILD.bazel, pkg/commands/patch/patch.go, pkg/commands/validate/BUILD.bazel, pkg/commands/validate/validate.go, vendor/k8s.io/klog/.travis.yml, vendor/k8s.io/klog/BUILD.bazel, vendor/k8s.io/klog/CONTRIBUTING.md, vendor/k8s.io/klog/LICENSE, vendor/k8s.io/klog/OWNERS, vendor/k8s.io/klog/README.md, vendor/k8s.io/klog/RELEASE.md, vendor/k8s.io/klog/SECURITY_CONTACTS, vendor/k8s.io/klog/code-of-conduct.md, vendor/k8s.io/klog/klog.go, vendor/k8s.io/klog/klog_file.go
klog and glog use define same flags and if you use one of those flag (such
as log_dir) in your command line, your program panics in runtime. So this PR
makes repo use klog exclusively.
All the changes to go files are done with sed and all the BUILD.bazel
files are updated with bazel run //:gazelle. bazel test ... runs
successfully.
=> Use klog (#207)

pkg/commands/build/build.go, pkg/commands/root.go
Inline doesn't make sense as a flag any longer, since you can only
inline during the build phase.
Work on #173
However, more work should be done to actually clean up this code.
=> Make inline not able to be set.

pkg/apis/bundle/v1alpha1/object_template_types.go, pkg/build/inline.go, pkg/build/inline_test.go
This PR adds a builder type for ObjectTemplates + inlining logic.
Additionally, this:
- Stops adding the inline annotation (TODO(self): remove completely)
- Refactors inlining to be clearer (with helper methods)
- Refactors the inlining test to check for substrs (good enough, clearer).
Partial work on #201
=> Add an ObjectTemplateBuilder type.

examples/cluster/etcd/etcd-component.yaml, pkg/build/BUILD.bazel, pkg/build/inline.go, pkg/build/inline_integration_test.go, pkg/build/inline_test.go, pkg/build/path_rewriter.go, pkg/commands/build/BUILD.bazel, pkg/commands/cmdlib/bundleio.go, pkg/commands/cmdlib/bundleio_test.go, pkg/commands/export/BUILD.bazel, pkg/commands/filter/BUILD.bazel, pkg/testutil/componentsuite/componentsuite.go
This PR adds relative path support back. You can now specify relative
paths for any of the file URLs. File-paths will be rewritten only if the
child-file path (e.g., an object in a component) is a relative path.
Fixes: #227
=> Add relative-path support back.

pkg/apis/bundle/v1alpha1/object_template_types.go, pkg/commands/cmdlib/BUILD.bazel, pkg/commands/cmdlib/bundleio_test.go, pkg/commands/cmdlib/cmdio.go, pkg/commands/cmdrunner/BUILD.bazel, pkg/commands/cmdrunner/execute_cmd.go, pkg/commands/cmdtest/BUILD.bazel, pkg/commands/cmdtest/fake_cmd_io.go, pkg/commands/cmdtest/fake_exiter.go, pkg/commands/cmdtest/fake_stdio.go, pkg/commands/find/get_command.go, pkg/commands/patch/patch.go, pkg/commands/root.go, pkg/commands/version/BUILD.bazel, pkg/commands/version/version_test.go, pkg/testutil/BUILD.bazel, pkg/testutil/fake_reader_writer.go
This PR adds an integration test framework for commands by mocking out
stdio, fileio, and exiting. Additionally I refactored the bundleio test
slightly to use the new fakes and I used the integration test framework
for the easiest command: `bundlectl version`.
Still to do:
- Use the CmdIO struct everywhere.
- Make more integration tests.
Partial work on #126
=> Add a intgration test framework for bundlectl commands.

pkg/find/finder.go
This PR changes finder.ComponentVersions to return references instead of objects. Just makes this method a bit easier to work with.
=> Change finder.ComponentVersions to return references

pkg/options/gotmpl/go_template_applier.go, pkg/options/multi/BUILD.bazel, pkg/options/multi/multi.go, pkg/options/multi/multi_test.go
This allows chaining together appliers. By default, options are first
applied to go templates, and then patches are applied. This is a good
default ordering because it means patches can be later applied to go
templates.
Fixes: #249
=> Add a multi-applier applier

pkg/build/BUILD.bazel, pkg/build/inline_benchmark_test.go, pkg/build/patchbuild_benchmark_test.go, pkg/commands/build/BUILD.bazel, pkg/options/gotmpl/BUILD.bazel, pkg/options/gotmpl/go_template_applier_benchmark_test.go, pkg/options/patchtmpl/BUILD.bazel, pkg/options/patchtmpl/patch_benchmark_test.go
These are only basic tests, but I'm getting 
BenchmarkBuildAndInline_Component-12    	     500	   2733579 ns/op
BenchmarkBuildAndPatch_Component-12     	    2000	   1076068 ns/op
on my local pc, and I'm even hitting the file system in places.  I don't think it matters.  
Think it's a waste of time to benchmark this  Our db latency is multiple levels of magnitude larger than this, so it doesn't really make much sense to care about this.  .  
Patch tests:
BenchmarkGoTemplateApplier-12    	    3000	    620792 ns/op
BenchmarkPatchTemplateApplier-12    	   10000	    137668 ns/op
=> Basic benchmarks

pkg/deps/annotation_matcher.go, pkg/deps/annotation_matcher_test.go, pkg/deps/resolve.go
1.  Don't return an error from ComponentVersions. Just return an empty list.
This is a cleaner / more standard API.
2.  For annotation matching, if the list of values is empty, match anything.
Fixes: #276.
=> Two cleanups for dependency resolution:

pkg/deps/meta.go
This shouldn't happen, but has happened before due to parsing bugs. In
this case, throw an error rather than panic'ing.
=> Add an error in the case of nil objects.

examples/BUILD.bazel, examples/bazel_init_test.go, examples/component/test-suite.yaml, examples/examples_test.go, pkg/build/inline.go, pkg/build/inline_test.go, pkg/build/path_rewriter.go, pkg/commands/cmdlib/bundleio.go, pkg/commands/cmdlib/bundleio_test.go, pkg/converter/converter_test.go, pkg/testutil/componentsuite/componentsuite.go, pkg/testutil/componentsuite/schema.go, pkg/testutil/testutil.go
Now, in bundleio, make the component / bundle files absolute as soon as
possible and return an error in the inliner if they are not absolute.
Also: Fix relative path issues in component testsuite
Fixes:#279
Fixes #274
=> Some fixes to relative path handling

pkg/build/inline.go
Otherwise resolving a relative path inside a ComponentBuilder inside a
BundleBuilder resolves relative to cwd, not to the ComponentBuilder
path.
=> Use the absolute path when resolving components

WORKSPACE, examples/BUILD.bazel, examples/cluster/BUILD.bazel, examples/component/BUILD.bazel, examples/component/test-suite.yaml, examples/jsonnet/BUILD.bazel, examples/jsonnet/bazel_init_test.go, examples/jsonnet/builder.yaml, examples/jsonnet/jsonnet_test.go, examples/jsonnet/test-suite.yaml, examples/patchbuilder/BUILD.bazel, examples/patchbuilder/test-suite.yaml, pkg/commands/cmdrunner/BUILD.bazel, pkg/commands/cmdtest/BUILD.bazel, pkg/options/common.go, pkg/options/gotmpl/go_template_applier.go, pkg/options/multi/BUILD.bazel, pkg/options/multi/multi.go, pkg/options/patchtmpl/scheme.go, pkg/testutil/BUILD.bazel, pkg/testutil/componentsuite/BUILD.bazel, pkg/testutil/componentsuite/componentsuite.go, pkg/testutil/componentsuite/schema.go, pkg/testutil/componentsuite/validate.go
This PR modifies the component test-suite to have a canKubeDeserialize
field that checks whether objects can be deserialized using the internal
Kubernetes deserialization logic. This relies on the schema in the
patchtmpl (which perhaps should be put in a more common place, like
`pkg/options`)
A couple smaller changes:
- disable jsonnet importing example for now
- add jsonnet to the multi-applier
- add a deserialize test case to all examples
- add a test case for jsonnet
=> Enable object deserialization test in component testsuite.

pkg/build/patchbuild.go, pkg/build/patchbuild_test.go
In trying to use JSONPatch with a PatchTemplateBuilder, I noticed that the PatchType field was not getting carried through to the created PatchTemplate. This change addresses that.
I also added a testcase (which previously failed).
=> Preserve PatchType when creating PatchTemplate from builder

pkg/options/gotmpl/go_template_applier.go, pkg/options/gotmpl/go_template_applier_test.go, pkg/options/patchtmpl/patch.go, pkg/options/patchtmpl/patch_benchmark_test.go, pkg/options/patchtmpl/patch_test.go
This commit lets the caller specify text/template options when creating a gotmpl applier.  The only meaningful option to pass is `missingkey={ignore,error,zero}`, to control the behavior when the template references an unset variable.
=> gotmpl Applier: Add text/template options config

pkg/apis/bundle/v1alpha1/helpers.go, pkg/apis/bundle/v1alpha1/helpers_test.go
This is an analogous function to the existing ComponentReference() on *Component.
=> Add func ComponentSetReference() on *ComponentSet.

pkg/options/patchtmpl/BUILD.bazel, pkg/options/patchtmpl/scheme.go
This change allows clients to patch CSIDriver and CSINode objects in
cluster bundles. These types were added to v1beta1 in kubernetes 1.14.0.
Tested: bazel test //...
=> Add storage/v1beta1 to default patcher

pkg/options/patchtmpl/BUILD.bazel, pkg/options/patchtmpl/scheme.go
This change allows clients to patch webhook objects in cluster bundles. `admissionregistration.k8s.io/v1beta1` is available since kubernetes 1.9
=> Add webhook v1beta1 to default patcher

examples/templatebuilder/BUILD.bazel, examples/templatebuilder/README.md, examples/templatebuilder/bazel_init_test.go, examples/templatebuilder/builder.yaml, examples/templatebuilder/component_test.go, examples/templatebuilder/etcd-template.yaml, examples/templatebuilder/template-builder.yaml, examples/templatebuilder/test-suite.yaml
This PR adds a new (go) template builder example to the `examples/` directory.
=> Add a TemplateBuilder example.

pkg/filter/filter.go
The invert match should be implemented in the underlying `matches` function, or else functions like `MatchesComponent` and `MatchesObject` won't have the support.
And please note that they are used by patch.go https://github.com/GoogleCloudPlatform/k8s-cluster-bundle/blob/master/pkg/options/patchtmpl/patch.go#L359
=> Support invert match in the internal function `matches`.

examples/patchbuilder/deployment-patch-builder.yaml
With the change, running `bazel test //examples/patchbuilder/...` failed with:
--- FAIL: TestComponentSuite/Deserialize_Objects (0.00s)
componentsuite.go:117: got error "cannot build PatchTemplate from PatchTemplateBuilder \"\": error executing template: template: ptb:12:15: executing \"ptb\" at <ge .Port 1>: error calling ge: incompatible types for comparison" but expected no error
=> Modify examples/patchbuilder/deployment-patch-builder.yaml to reproduce number comparison issue.

examples/patchbuilder/deployment-patch-builder.yaml, pkg/build/patchbuild.go, pkg/converter/converter_test.go, pkg/options/openapi/validate.go, pkg/options/patchtmpl/patch_test.go
Here, I added test cases for patch template builder edgecase.
There are two issues:
1. Mixing go-templates and patch template builders don't work terribly
well. Because the patch template builder has built into a secondary
template, any complex go-template properties need to be applied in
the build phase.
2. The YAML/JSON conversion schema can't tell the difference between an
integer and a float.
These are unfortunately limitations of the patch template design.
Here, I add a possible solution (put the go-template stuff in
patch-building).
An alternative is to use ObjectTemplateBuilders.
=> Add test cases for patch template builder edgcase
