GoogleCloudPlatform/k8s-cluster-bundle

pkg/testutil/testdata/example-bundle.yaml
pkg/testutil/testdata/kubeproxy/kubeproxy.yaml
pkg/transformer/inline.go
pkg/transformer/inline_test.go

Add support for inlining multidoc YAML. Also, fix some error-passing in the process. 
Fixes: https://github.com/GoogleCloudPlatform/k8s-cluster-bundle/issues/29

Add support for inline YAML multi-docs.

---

pkg/transformer/inline.go

Remove an erroneous nil check and add better messaging for the previous nil
check.

Fix nil assertion

---

pkg/transformer/inline.go
pkg/transformer/inline_test.go

Fixes a bug during inlining raw-text files: the files weren't getting
cleared. Add a test that ensures the files are cleared.

Fix a bug in the inline process.

---

pkg/converter/kube.go

Fix a lint error where I misnamed a method-name in a comment.

Fix a lint error

---

pkg/converter/name.go
pkg/converter/name_test.go
pkg/transformer/config_map_maker.go
pkg/transformer/config_map_maker_test.go

Add license headers to some files that I missed.

Add license headers to some files

---

pkg/transformer/inline.go
pkg/transformer/inline_test.go

Fix inlining for raw text.

---

pkg/apis/bundle/v1alpha1/component_types.go
pkg/apis/bundle/v1alpha1/helpers.go
pkg/apis/bundle/v1alpha1/helpers_test.go
pkg/core/core.go
pkg/files/url_scheme.go
pkg/filter/filter.go
pkg/inline/inline.go
pkg/inline/path_rewriter.go
pkg/maker/maker.go
pkg/maker/rawyamltmpl/raw_text_maker.go
pkg/validation/validate_component.go
pkg/validation/validate_name.go
pkg/validation/validate_name_test.go

I've been lax about running go vet, and lint. This PR cleans up some of these issues.

Fix various bugs, lint warnings, go-vet warnings, docs issues.

---

pkg/commands/filter/filter.go
pkg/filter/filter.go
pkg/filter/filter_test.go
pkg/maker/common.go
pkg/maker/rawyamltmpl/raw_text_maker.go

Follow-up comments to previous PR (#103): Rename Filterer to Filter
Progress on #104

Rename Filterer to Filter

---

pkg/converter/converter_test.go

Added one more convert iteration from Yaml to Object.
Added few checks to be sure that Object field value matches original YAML values.
Fixes https://github.com/GoogleCloudPlatform/k8s-cluster-bundle/issues/98

Added one more convert iteration from Yaml to Object

---

pkg/converter/converter_test.go

Added few more testcases to converte_test:
1)YAML->Bundle->YAML->Bundle
2)YAML->Component->YAML->Component
Fixes https://github.com/GoogleCloudPlatform/k8s-cluster-bundle/issues/133

Added Bundle and component converters test

---

examples/component/README.md
examples/component/etcd-component.yaml
examples/component/etcd-server.yaml

Small PR to improve some docs and examples about patching.

Improve docs, examples about patching.

---

pkg/converter/converter_test.go
pkg/converter/demuxer.go

Added ToYAMLString() and ToJSONString() methods to converter.
Added test to check type conversions.
Fixes: https://github.com/GoogleCloudPlatform/k8s-cluster-bundle/issues/140

Added ToYAMLString() and ToJSONString() methods to converter

---

pkg/options/openapi/BUILD.bazel
pkg/options/openapi/default.go
pkg/options/openapi/default_test.go
pkg/options/openapi/validate.go

Add openapi defaulting, which will be used by the patch builder.

---

examples/BUILD.bazel
examples/component/BUILD.bazel
examples/component/bazel_init_test.go
examples/component/component_test.go
examples/component/etcd-component-test.yaml
examples/component/patches.yaml

This adds a test-suite test for the component in the `examples/component` directory

Add a test-suite for the component example

---

examples/component/bazel_init_test.go
examples/component/component_test.go
examples/patchbuilder/bazel_init_test.go
examples/patchbuilder/component_test.go

basically, change the test packages for the examples dir to be foo_test

Fix up some tests to make some imports/tooling happier.

---

pkg/build/patchbuild.go
pkg/commands/cmdlib/bundleio.go
pkg/commands/patch/patch.go

Remove some debug logging that is not useful, and bump up the
verbosity required on others.

Less logging

---

pkg/commands/version/add_commands.go
pkg/validate/validate_component.go

Fix lint errors.

---

pkg/apis/bundle/v1alpha1/object_template_types.go
pkg/commands/build/get_command.go
pkg/commands/export/get_command.go
pkg/commands/filter/get_command.go
pkg/commands/find/get_command.go
pkg/commands/patch/get_command.go
pkg/commands/validate/get_command.go
pkg/commands/version/get_command.go
pkg/find/finder.go
pkg/validate/validate_component_test.go

- Add package comments.
- Fix a typo

Fix some lint errors

---

pkg/commands/BUILD.bazel
pkg/commands/build/BUILD.bazel
pkg/commands/export/BUILD.bazel
pkg/commands/filter/BUILD.bazel
pkg/commands/generate/BUILD.bazel
pkg/commands/generate/get_command.go
pkg/commands/root.go
pkg/generate/BUILD.bazel
pkg/generate/generate.go

Made new pr.  rebasing had was messy, easier to just open new pr. 
Added templates instead of the simple string replace.  
Still working on the extra patching and test suite integration on this pr and that can either be in this or a separate pr, doesn't matter from my perspective.

Init command

---

hack/update-codegen.sh
pkg/apis/bundle/v1alpha1/component_types.go
pkg/apis/bundle/v1alpha1/zz_generated.deepcopy.go

List types should use ListMeta rather than ObjectMeta.
Fixes: #250

Fix list meta.

---

cmd/bundlectl/integration_tests/BUILD
pkg/options/patchtmpl/BUILD.bazel
pkg/options/patchtmpl/scheme.go

Add apps/v1beta2 to patcher scheme.

Add apps/v1beta2 to patcher scheme

---

pkg/options/patchtmpl/patch.go

Splited `makePatches` function and moved fetch part into separated function to be able check if there is no patch templates outside the function.
Fixes: https://github.com/GoogleCloudPlatform/k8s-cluster-bundle/issues/259

Added check if there is no patch templates

---

WORKSPACE

Update go rules, gazelle, and go tool chain in attempt to fix the build.

Update go rules, gazelle, and go tool chain in attempt to fix the build.

---

pkg/apis/bundle/v1alpha1/object_template_types.go
pkg/apis/bundle/v1alpha1/requirement_types.go
pkg/deps/annotation_matcher.go
pkg/options/jsonnet/jsonnet_applier.go
pkg/options/patchtmpl/patch.go

Some lint, gobug issues, and types that I discovered while trying to import the cluster bundle internally.

Fix golint, gobug, typos

---

pkg/validate/BUILD.bazel
pkg/validate/validate_component.go
pkg/validate/validate_component_test.go

Use standard semver library instead of the weird thing I wrote.

---

cmd/bundlectl/BUILD.bazel
cmd/bundlectl/main.go

This re-adds the logtostderr message flag override for compatibility.

Add logtostderr override back

---

pkg/converter/unstructured.go

Remove Initializers when converting ObjectMeta

1.16 compatibility changes

---

pkg/options/patchtmpl/BUILD.bazel
pkg/options/patchtmpl/scheme.go
pkg/version/version.go

Update the release branch so we can do a 0.12.3 release.
+ update the version

Update the 0.12 release branch

---

pkg/options/patchtmpl/BUILD.bazel
pkg/options/patchtmpl/scheme.go
pkg/version/version.go

Update Release 0.12, to set up for v0.12.5

Update Release 0.12

---

examples/templatefiles/BUILD.bazel
examples/templatefiles/README.md
examples/templatefiles/bazel_init_test.go
examples/templatefiles/builder.yaml
examples/templatefiles/component_test.go
examples/templatefiles/etcd-template.yaml
examples/templatefiles/test-suite.yaml
pkg/apis/bundle/v1alpha1/builder_types.go
pkg/build/inline.go
pkg/build/inline_test.go

Fixes: https://github.com/GoogleCloudPlatform/k8s-cluster-bundle/issues/305

Add TemplateFiles to ComponentBuilder

---

pkg/filter/filter.go

Cherrypick the fix into release-0.12

[Cherrypick] Support invert match in the internal function `matches`.

---

pkg/version/version.go

Update the CLI prior to doing a 0.13 release

Update minor version of CLI for cluster bundle

---

pkg/options/patchtmpl/patch.go
pkg/options/patchtmpl/patch_test.go

Add a builtin helper for converting any type to floats, to make
comparisons easier.

Add a float convert helper for patch templates.

---

go.mod
pkg/apis/bundle/v1alpha1/builder_types.go
pkg/apis/bundle/v1alpha1/object_template_types.go
pkg/apis/bundle/v1alpha1/patch_template_types.go
pkg/build/BUILD.bazel
pkg/build/inline.go
pkg/build/inline_test.go
pkg/build/patchbuild.go
pkg/build/patchbuild_test.go
pkg/internal/BUILD.bazel
pkg/internal/templater.go
pkg/options/gotmpl/go_template_applier.go
pkg/options/gotmpl/go_template_applier_test.go
pkg/options/patchtmpl/patch.go

An annotation is much safer to role out than a new schema change, which is much more heavy weight.

Change safe yaml to be an annotation rather than schema change.
